openapi: 3.0.0
info:
  title: backend-ecommerce application
  description: Backend ECommerce application
  version: v1.0.0
  contact:
    email: avi.rohit13@hotmail.com
    url: https://avinash-sharma.netlify.com


servers:
  - url: "{protocal}://localhost:4000/api/{version}"
    description: for local hosting servers

    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocal:
        default: http
        enum:
          - http
          - https

components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: token

    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: returns a greet message
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: "my string"
        400:
          description: Bad Request
        500:
          description: Internal Server Error